"""add price fields

Revision ID: 20260304_prices
Revises: 
Create Date: 2026-03-04 19:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260304_prices'
# Вставте сюди ID попередньої міграції, якщо вона є (наприклад, 'a1b2c3d4e5f6')
down_revision: Union[str, None] = '20240522_add_discogs_cache_table' 
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column('vinyls', sa.Column('median_price', sa.Float(), nullable=True))
    op.add_column('vinyls', sa.Column('highest_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('vinyls', 'highest_price')
    op.drop_column('vinyls', 'median_price')
    # ### end Alembic commands ###