"""add is_wishlist to vinyls

Revision ID: 3b1c4d5e6f7g
Revises: 4974433d35a0
Create Date: 2026-03-02 21:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1c4d5e6f7g'
down_revision: Union[str, None] = '4974433d35a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vinyls', sa.Column('is_wishlist', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vinyls', 'is_wishlist')
    # ### end Alembic commands ###